# Generated by Django 4.1 on 2022-08-22 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_examplemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExampleModel',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
