# Generated by Django 4.1 on 2022-08-22 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_customer_order_customer_shippingaddress_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
