# Generated by Django 4.1 on 2022-09-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_customer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_completed',
            field=models.DateTimeField(null=True),
        ),
    ]
