# Generated by Django 4.1 on 2022-10-06 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_product_discount_price_product_order_limit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderItem',
            new_name='CartItem',
        ),
    ]
