# Generated by Django 4.1 on 2022-10-06 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_rename_orderitem_cartitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Cart',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='order',
            new_name='cart',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='order',
            new_name='cart',
        ),
    ]
