# Generated by Django 4.1 on 2022-10-18 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='date_completed',
            new_name='created',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='date_ordered',
        ),
        migrations.AddField(
            model_name='cart',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
