# Generated by Django 4.1 on 2022-10-18 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_rename_date_completed_cart_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='complete',
        ),
        migrations.AddField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
