# Generated by Django 4.1 on 2022-10-18 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_remove_cart_complete_order_transaction_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='order',
            new_name='cart',
        ),
    ]
