# Generated by Django 4.1 on 2022-10-18 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_rename_order_orderitem_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='cart',
            new_name='order',
        ),
    ]
