# Generated by Django 4.1 on 2022-10-18 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_rename_cart_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='is_checked',
            field=models.BooleanField(default=True),
        ),
    ]
