# Generated by Django 4.1 on 2022-10-18 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_cartitem_is_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(choices=[(0, 'Waiting for Payment'), (1, 'Payment Received'), (2, 'Preparing'), (3, 'Prepared'), (4, 'Shipping'), (5, 'Delivered'), (6, 'Cancelled')], default=0, verbose_name='Order Status'),
        ),
    ]
