# Generated by Django 4.1 on 2022-10-18 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(choices=[(0, 'Waiting for Payment'), (1, 'Payment Received'), (2, 'Preparing Order'), (3, 'Order is Prepared'), (4, 'Order in Shipping'), (5, 'Order is Delivered'), (6, 'Cancelled')], default=0, verbose_name='Order Status'),
        ),
    ]
