# Generated by Django 4.1 on 2022-10-20 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_order_complete_order_transaction_id'),
        ('store', '0032_alter_order_order_status'),
    ]

    operations = [
    ]
