# Generated by Django 4.1 on 2022-10-20 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_merge_20221020_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='complete',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(choices=[(0, 'Waiting for Payment'), (1, 'Preparing Order'), (2, 'Order is Prepared'), (3, 'Order in Shipping'), (4, 'Order is Delivered'), (5, 'Cancelled')], default=0, verbose_name='Order Status'),
        ),
    ]
