# Generated by Django 4.1 on 2022-11-13 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_remove_shippingaddress_cart_shippingaddress_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_unit_price', models.FloatField()),
                ('current_discount', models.FloatField()),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='SellingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.FloatField()),
                ('quantity', models.IntegerField(default=0)),
                ('discount', models.FloatField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.customer')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='BuyingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.FloatField()),
                ('purchase_price', models.FloatField()),
                ('quantity', models.IntegerField(default=0)),
                ('product_source_name', models.CharField(max_length=200, null=True)),
                ('buying_time', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateTimeField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='store.product')),
            ],
        ),
    ]
