# Generated by Django 4.1 on 2022-11-14 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_stock_sellingitem_buyingitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BuyingItem',
            new_name='PurchasedItem',
        ),
        migrations.RenameModel(
            old_name='SellingItem',
            new_name='SoldItem',
        ),
    ]
