# Generated by Django 4.1 on 2022-11-20 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0038_remove_product_order_limit_stock_order_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='item_count',
            field=models.IntegerField(default=0),
        ),
    ]
