# Generated by Django 4.1 on 2022-11-20 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0039_stock_item_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='item_count',
        ),
    ]
