# Generated by Django 4.1 on 2022-11-20 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0040_remove_stock_item_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='current_unit_price',
        ),
    ]
