# Generated by Django 4.1 on 2022-11-21 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0041_remove_stock_current_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='solditem',
            name='purchase_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='solditem',
            name='discount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='solditem',
            name='unit_price',
            field=models.FloatField(default=0.0),
        ),
    ]
