# Generated by Django 4.1 on 2022-11-23 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0042_solditem_purchase_price_alter_solditem_discount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solditem',
            name='customer',
        ),
        migrations.AddField(
            model_name='solditem',
            name='order',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='store.order'),
            preserve_default=False,
        ),
    ]
