# Generated by Django 4.1 on 2022-11-28 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0043_remove_solditem_customer_solditem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseditem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.product'),
        ),
    ]
