# Generated by Django 4.1 on 2022-11-28 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0044_alter_purchaseditem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solditem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.product'),
        ),
    ]
