# Generated by Django 4.1 on 2022-11-28 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0045_alter_solditem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='current_discount',
            field=models.FloatField(default=0.0),
        ),
    ]
