# Generated by Django 4.1 on 2022-12-27 09:15

import background_tasks.enums
from django.db import migrations, models
import django.db.models.deletion
import django_enum_choices.choice_builders
import django_enum_choices.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_celery_beat', '0016_alter_crontabschedule_timezone'),
        ('store', '0046_alter_stock_current_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSendingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', django_enum_choices.fields.EnumChoiceField(choice_builder=django_enum_choices.choice_builders.value_value, choices=[('Active', 'Active'), ('Disabled', 'Disabled')], default=background_tasks.enums.SetupStatus['active'], enum_class=background_tasks.enums.SetupStatus, max_length=8)),
                ('time_interval', django_enum_choices.fields.EnumChoiceField(choice_builder=django_enum_choices.choice_builders.value_value, choices=[('1 min', '1 min'), ('5 mins', '5 mins'), ('1 hour', '1 hour')], default=background_tasks.enums.TimeInterval['five_mins'], enum_class=background_tasks.enums.TimeInterval, max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('immediate_email', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='immediate_task', to='django_celery_beat.periodictask')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='store.order')),
                ('scheduled_email', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_task', to='django_celery_beat.periodictask')),
            ],
            options={
                'verbose_name': 'EmailSendingTask',
                'verbose_name_plural': 'EmailSendingTasks',
            },
        ),
    ]
