# Generated by Django 4.1 on 2023-01-02 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0016_alter_crontabschedule_timezone'),
        ('background_tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsendingtask',
            name='immediate_email',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='immediate_email', to='django_celery_beat.periodictask'),
        ),
        migrations.AlterField(
            model_name='emailsendingtask',
            name='scheduled_email',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_email', to='django_celery_beat.periodictask'),
        ),
    ]
